# Generated by Django 4.2.5 on 2023-10-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome do estádio', max_length=200, verbose_name='Nome')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
