# Generated by Django 4.2.4 on 2023-10-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Jogador', max_length=150, verbose_name='Nome')),
                ('apelido', models.CharField(help_text='Apelido do Jogador', max_length=150, verbose_name='Apelido')),
                ('dataNascimento', models.DateField(help_text='Data de Nascimento do Jogador', verbose_name='Data de Nascimento')),
                ('numero', models.IntegerField(help_text='Numero do Jogador', verbose_name='Numero')),
                ('posição', models.CharField(help_text='Posição do Jogador', max_length=150, verbose_name='Posição')),
                ('qualidade', models.IntegerField(help_text='Posição do Jogador', verbose_name='Qualidade')),
                ('cartoes', models.IntegerField(help_text='Cartoes que o Jogador Possui', verbose_name='Cartões')),
                ('suspensao', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Estadio',
        ),
    ]
