# Generated by Django 4.2.3 on 2023-10-31 14:16

from django.db import migrations, models
import django.db.models.deletion
import loterica.models.cliente
import loterica.models.conta


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('basemodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loterica.basemodels')),
                ('cod', models.CharField(help_text='Codigo do cliente', max_length=10, verbose_name='codigo')),
                ('nome', models.CharField(help_text='Nome do Cliente', max_length=100, validators=[loterica.models.cliente.validaNome], verbose_name='Nome')),
                ('cpf', models.CharField(help_text='CPf do cliente', max_length=11, unique=True, verbose_name='CPF')),
                ('email', models.CharField(help_text='E-mail do Cliente', max_length=100, verbose_name='E-mail')),
            ],
            options={
                'abstract': False,
            },
            bases=('loterica.basemodels',),
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('basemodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loterica.basemodels')),
                ('numero', models.IntegerField(help_text='Numero da Conta', verbose_name='Número')),
                ('digito', models.CharField(help_text='Digito da Conta bancaria', max_length=1, verbose_name='Digito')),
                ('tipo', models.CharField(help_text='Tipo de Conta Bancaria', max_length=20, validators=[loterica.models.conta.validaTipo], verbose_name='Tipo')),
                ('agencia', models.CharField(help_text='Agencia Bancaria', max_length=4, verbose_name='Agencia')),
                ('saldo', models.FloatField(help_text='Saldo da Conta', verbose_name='Saldo')),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loterica.cliente')),
            ],
            options={
                'abstract': False,
            },
            bases=('loterica.basemodels',),
        ),
    ]
